version: '3.9'
services:
  i.database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes: 
      - .database:/var/lib/postgresql/data
