version: '3.9'
services:
  i.database:
    image: postgres:14.1-alpine
    restart: always
    expose:
      - 5432
    volumes: 
      - .database:/var/lib/postgresql/data
    environment:
     POSTGRES_HOST_AUTH_METHOD: trust

  i.service:
    build: .
    restart: always
    ports:
      - 80:80
    environment:
      API_PORT: 80
      DATABASE_URL: postgresql://postgres@i.database
