version: '3.9'
services:
  i.database:
    image: postgres:14.1-alpine
    restart: always
    expose:
      - 5432
    volumes: 
      - .database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  i.service:
    build: .
    restart: always
    ports:
      - 80:80
    environment:
      API_PORT: 80
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@i.database/${POSTGRES_DB}
